"""
Caption Optimizer Module.

Uses YOLOv8 object detection results to validate and re-rank 
multiple caption candidates generated by beam search.
"""


class CaptionOptimizer:
    """
    Validates and re-ranks caption candidates based on alignment 
    with detected objects from YOLOv8.
    """
    
    # Maps YOLO COCO class names to likely caption synonyms.
    # Captions from Flickr8K rarely say "person" — they say "man", "woman", etc.
    SYNONYM_MAP = {
        "person":     ["man", "woman", "boy", "girl", "child", "kid", "people",
                       "player", "rider", "worker", "lady", "guy", "men", "women",
                       "children", "crowd", "group", "surfer", "skier", "biker",
                       "cyclist", "hiker", "climber", "swimmer"],
        "dog":        ["dog", "dogs", "puppy", "pup", "canine"],
        "cat":        ["cat", "cats", "kitten", "kitty", "feline"],
        "car":        ["car", "cars", "vehicle", "automobile", "sedan"],
        "bicycle":    ["bicycle", "bike", "cycling"],
        "motorcycle": ["motorcycle", "motorbike", "bike"],
        "bus":        ["bus", "buses"],
        "truck":      ["truck", "trucks", "lorry"],
        "boat":       ["boat", "boats", "ship", "canoe", "kayak", "vessel"],
        "horse":      ["horse", "horses", "pony", "stallion", "mare"],
        "skateboard": ["skateboard", "skating", "skate"],
        "surfboard":  ["surfboard", "surfing", "surf"],
        "frisbee":    ["frisbee", "disc", "disk"],
        "sports ball":["ball", "soccer", "football", "baseball", "tennis"],
        "kite":       ["kite", "kites"],
        "umbrella":   ["umbrella", "umbrellas"],
        "bench":      ["bench", "benches", "seat"],
        "bird":       ["bird", "birds"],
        "backpack":   ["backpack", "bag", "pack"],
        "handbag":    ["bag", "purse", "handbag"],
        "tie":        ["tie", "necktie"],
        "snowboard":  ["snowboard", "snowboarding"],
        "skis":       ["ski", "skis", "skiing", "skier"],
        "tennis racket": ["racket", "tennis"],
        "bottle":     ["bottle", "bottles"],
        "chair":      ["chair", "chairs", "seat"],
        "couch":      ["couch", "sofa"],
        "dining table": ["table", "tables"],
        "train":      ["train", "trains", "locomotive", "railway"],
        "airplane":   ["airplane", "plane", "aircraft", "jet"],
        "fire hydrant": ["hydrant"],
        "stop sign":  ["sign"],
        "traffic light": ["light", "signal"],
    }
    
    def __init__(self, alpha=0.6, beta=0.4):
        """
        Args:
            alpha (float): Weight for the beam search language model score.
            beta (float):  Weight for the YOLO object alignment score.
        """
        self.alpha = alpha
        self.beta = beta
        
        # Build a reverse lookup: word -> set of YOLO classes it could represent
        self._word_to_classes = {}
        for yolo_class, synonyms in self.SYNONYM_MAP.items():
            for word in synonyms:
                if word not in self._word_to_classes:
                    self._word_to_classes[word] = set()
                self._word_to_classes[word].add(yolo_class)
    
    def _get_detected_class_set(self, detected_objects):
        """Extracts the unique set of class names from YOLO detections."""
        return set(obj["class"] for obj in detected_objects)
    
    def _get_synonyms(self, yolo_class):
        """Returns the set of caption words that can refer to a YOLO class."""
        return set(self.SYNONYM_MAP.get(yolo_class, [yolo_class]))
    
    def score_caption(self, caption_words, detected_objects):
        """
        Computes how well a caption aligns with the detected objects.
        
        Args:
            caption_words (list of str): Tokenized caption words (lowercase).
            detected_objects (list of dict): YOLO detection results.
            
        Returns:
            float: Alignment score between 0.0 and 1.0.
            dict:  Detailed matching info.
        """
        detected_classes = self._get_detected_class_set(detected_objects)
        
        if not detected_classes:
            return 0.5, {"matched": [], "missed": [], "extra": []}
        
        caption_word_set = set(caption_words)
        
        # Object Recall: what fraction of detected objects are mentioned?
        matched = []
        missed = []
        for cls in detected_classes:
            synonyms = self._get_synonyms(cls)
            if synonyms & caption_word_set:  # intersection
                matched_word = (synonyms & caption_word_set).pop()
                matched.append((cls, matched_word))
            else:
                missed.append(cls)
        
        recall = len(matched) / len(detected_classes) if detected_classes else 0.0
        
        # Object Precision: are caption nouns actually in the image?
        # Check if any caption words refer to objects NOT detected
        extra = []
        for word in caption_words:
            if word in self._word_to_classes:
                possible_classes = self._word_to_classes[word]
                if not (possible_classes & detected_classes):
                    extra.append(word)
        
        # Penalize for mentioning objects not in the image
        precision_penalty = len(extra) * 0.1  # small penalty per hallucinated object
        
        # Combined alignment score
        alignment = max(0.0, recall - precision_penalty)
        alignment = min(1.0, alignment)
        
        details = {
            "matched": matched,
            "missed": missed,
            "extra": extra,
            "recall": recall,
        }
        
        return alignment, details
    
    def optimize(self, candidates, detected_objects, vocab):
        """
        Re-ranks caption candidates using a weighted combination of 
        beam search score and YOLO alignment score.
        
        Args:
            candidates (list of tuple): Each is (word_indices, beam_score) from top-K beam search.
            detected_objects (list of dict): YOLO detection results.
            vocab (object): Vocabulary object (has itos mapping).
            
        Returns:
            list of dict: Re-ranked candidates, each with caption text, 
                          combined score, and alignment details.
        """
        if not candidates:
            return []
        
        # Normalize beam scores to 0-1 range for fair combination
        beam_scores = [score for _, score in candidates]
        max_beam = max(beam_scores)
        min_beam = min(beam_scores)
        beam_range = max_beam - min_beam if max_beam != min_beam else 1.0
        
        results = []
        for word_indices, beam_score in candidates:
            # Convert indices to words
            words = []
            for idx in word_indices:
                word = vocab.itos[idx]
                if word == "<end>":
                    break
                if word not in ["<start>", "<pad>"]:
                    words.append(word)
            
            caption_text = " ".join(words)
            
            # Normalize beam score to 0-1
            norm_beam = (beam_score - min_beam) / beam_range if beam_range != 0 else 1.0
            
            # Compute YOLO alignment
            alignment_score, details = self.score_caption(words, detected_objects)
            
            # Weighted combination
            combined = self.alpha * norm_beam + self.beta * alignment_score
            
            results.append({
                "caption": caption_text,
                "words": words,
                "beam_score": beam_score,
                "norm_beam_score": norm_beam,
                "alignment_score": alignment_score,
                "combined_score": combined,
                "details": details,
            })
        
        # Sort by combined score (highest first)
        results.sort(key=lambda x: x["combined_score"], reverse=True)
        return results
    
    def validate(self, caption_words, detected_objects):
        """
        Produces a human-readable validation report for a caption.
        
        Args:
            caption_words (list of str): Tokenized caption.
            detected_objects (list of dict): YOLO detections.
            
        Returns:
            str: Formatted validation report.
            str: Confidence level — "HIGH", "MEDIUM", or "LOW".
        """
        alignment, details = self.score_caption(caption_words, detected_objects)
        detected_classes = self._get_detected_class_set(detected_objects)
        
        lines = []
        
        # Matched objects
        for cls, word in details["matched"]:
            lines.append(f"  \u2713 {cls} \u2192 matched \"{word}\"")
        
        # Missed objects
        for cls in details["missed"]:
            lines.append(f"  \u2717 {cls} \u2192 not mentioned in caption")
        
        # Extra/hallucinated
        for word in details["extra"]:
            lines.append(f"  ? \"{word}\" \u2192 mentioned but not detected in image")
        
        total = len(detected_classes)
        matched_count = len(details["matched"])
        
        if total == 0:
            confidence = "N/A"
        elif matched_count == total:
            confidence = "HIGH"
        elif matched_count >= total * 0.5:
            confidence = "MEDIUM"
        else:
            confidence = "LOW"
        
        lines.append(f"  Caption Confidence: {confidence} ({matched_count}/{total} objects matched)")
        
        return "\n".join(lines), confidence

    def _extract_nouns(self, text):
        """Helper function to extract meaningful words from a caption."""
        stop_words = {
            "a", "an", "the", "is", "are", "was", "were", "and", "or", "but", 
            "in", "on", "at", "to", "with", "by", "of", "for", "it", "this", "that", "there", "some"
        }
        for p in ".,!?;:\"'-":
            text = text.replace(p, " ")
        words = text.lower().split()
        return [w for w in words if w not in stop_words and len(w) > 1]

    def refine_caption(self, caption, detected_objects):
        """
        Refines a caption based on alignment with YOLO-detected objects.
        
        Args:
            caption (str): The generated caption text.
            detected_objects (list of dict): YOLO detection results.
            
        Returns:
            str: The refined caption.
        """
        caption_objs = self._extract_nouns(caption)
        yolo_objs = list(self._get_detected_class_set(detected_objects))
        confidences = [obj["confidence"] for obj in detected_objects]

        # Agreement: Use synonym matching to accurately calculate intersection
        matched_yolo_objs = set()
        for y_obj in yolo_objs:
            if self._get_synonyms(y_obj) & set(caption_objs):
                matched_yolo_objs.add(y_obj)
                
        intersection = (set(caption_objs) & set(yolo_objs)) | matched_yolo_objs
        agreement = len(intersection) / max(len(set(yolo_objs)), 1)

        # YOLO confidence
        avg_conf = sum(confidences) / max(len(confidences), 1)

        # 🧠 Decision

        # Case 1: Strong agreement → trust caption
        if agreement >= 0.5:
            return caption

        # Case 2: Low YOLO confidence → trust caption
        if avg_conf < 0.4:
            return caption

        # Case 3: High YOLO confidence + low agreement → trust detection
        if avg_conf > 0.6 and agreement < 0.3:
            return "Scene contains: " + ", ".join(set(yolo_objs))

        # Case 4: Mixed → merge
        merged = list(set(caption_objs) | set(yolo_objs))
        return "Scene contains: " + ", ".join(merged)

